### ISSUE TITLE
加速度の値について

### ISSUE THREAD

**Issue by fig-shimooka** [rt-net/rt_usb_9axisimu_driver#47]
OS : Ubuntu 20.04
ROS2  : galactic
ファームウェアバージョン：2.0

本パッケージを使用してros2 topic echo /imu/data_rawをみたところ
静止状態で下記の出力が得られました。
```
  x: 0.814028564453125
  y: 0.01915361328125
  z: -0.062249243164062495
```
xに0.814m/s^2の加速度が加わっています。
静止状態ではZ軸に重力加速度が加わるので、xに加速度が出るのはおかしいような気がしますが、
これは正しい結果でしょうか？

![RT-USB-9axisIMU](https://github.com/rt-net/rt_usb_9axisimu_driver/assets/72783232/21268a0d-e926-4e0b-b64e-c8e0442860b9)
ちなみにこの面を天井側にしています。

```
---
header:
  stamp:
    sec: 1694062791
    nanosec: 21160921
  frame_id: imu_link
orientation:
  x: 0.0
  y: 0.0
  z: 0.0
  w: 1.0
orientation_covariance:
- -1.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
angular_velocity:
  x: 0.0
  y: 0.0021284503073101583
  z: 0.0
angular_velocity_covariance:
- 1.1280564100000001e-06
- 0.0
- 0.0
- 0.0
- 1.1280564100000001e-06
- 0.0
- 0.0
- 0.0
- 1.1280564100000001e-06
linear_acceleration:
  x: 0.814028564453125
  y: 0.01915361328125
  z: -0.062249243164062495
linear_acceleration_covariance:
- 0.0005356910249999999
- 0.0
- 0.0
- 0.0
- 0.0005356910249999999
- 0.0
- 0.0
- 0.0
- 0.0005356910249999999
```
